# Generated by Django 3.1.7 on 2021-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_pass',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
