# Generated by Django 3.1.7 on 2021-03-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_confirm_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_pass',
        ),
    ]
